export const USER_ACTION_TYPES = {
  SET_CURRENT_USER: "user/SET_CURRENT_USER",
  FETCH_CURRENT_USER_COINS_SUCCESS: "user/FETCH_CURRENT_USER_COINS_SUCCESS",
  FETCH_CURRENT_USER_COINS_START: "user/FETCH_CURRENT_USER_COINS_START",
};
