export const COIN_INFO_ACTION_TYPES = {
  SET_COIN_INFO: "coin-info/SET_COIN_INFO",
  FETCH_COIN_INFO_START: "coin-info/FETCH_COIN_INFO_START",
  FETCH_COIN_INFO_SUCCESS: "coin-info/FETCH_COIN_INFO_SUCCESS",
  FETCH_COIN_INFO_FAILED: "coin-info/FETCH_COIN_INFO_FAILED",
};
