export const META_COIN_ACTION_TYPES = {
  //SET_CURRENT_COINS: "metaCoins/SET_CURRENT_COINS",
  FETCH_COINS_START: "metaCoins/FETCH_COINS_START",
  FETCH_COINS_SUCCESS: "metaCoins/FETCH_COINS_SUCCESS",
  FETCH_COINS_FAILED: "metaCoins/FETCH_COINS_FAILED",
};
